// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86kvzC7DbMcms4Sm7sM8ltCcgTD_O6Sg',
    appId: '1:7799176998:android:6047b4388a986441a70be7',
    messagingSenderId: '7799176998',
    projectId: 'amarwebrtc',
    storageBucket: 'amarwebrtc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYyr1JaSTroyuQXcqrj_kyuVI8_lwUWYo',
    appId: '1:536317961776:ios:1494720ca04806446c2ff5',
    messagingSenderId: '536317961776',
    projectId: 'stayats-930d1',
    storageBucket: 'stayats-930d1.appspot.com',
    iosClientId:
        '536317961776-feumorfhq2p1rm6rb8noqn77m4c9af7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYyr1JaSTroyuQXcqrj_kyuVI8_lwUWYo',
    appId: '1:536317961776:ios:1494720ca04806446c2ff5',
    messagingSenderId: '536317961776',
    projectId: 'stayats-930d1',
    storageBucket: 'stayats-930d1.appspot.com',
    iosClientId:
        '536317961776-feumorfhq2p1rm6rb8noqn77m4c9af7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayats',
  );
}
